### PR TITLE
Add TFaaS documentation

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by vkuznet** [comment]
@aperloff I thought I resolved the conversation but apparently it did not show up in github. So I manually resolved it now. Please review again and merge or let me know if anything else is required.

**Review by aperloff — CHANGES_REQUESTED** [review]
@vkuznet The issue still remains. I see symbols &#10113; and &#10114;, but I don't see the symbol &#10112;. Why? Either add &#10112; or remove the other two.

**Comment by vkuznet** [comment]
ok, now I see what you mean. I added necessary changes, please review again.

**Review by aperloff — APPROVED** [review]
Looks good now.
+1

**Pull request merged**
